name: test-vcluster-cli
namespace: default

networkPeer: true

owner:
  user: admin

helmRelease:
  chart:
    version: 0.33.1
  values:
    controlPlane:
      distro:
        k8s:
          image:
            tag: v1.35.0
    sync:
      fromHost:
        csiDrivers:
          enabled: false
        csiStorageCapacities:
          enabled: false
        nodes:
          enabled: true
          selector:
            all: true
      toHost:
        persistentVolumes:
          enabled: true
        priorityClasses:
          enabled: true
        storageClasses:
          enabled: true

argocdApplicationTemplate:
  enabled: true

argocdApp:
  namespace: argocd
  project: default
  source:
    repoURL: ""
    targetRevision: HEAD
    path: chart/
  destination:
    server: https://kubernetes.default.svc
