apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.name }}-vci
  namespace: {{ .Values.argocdApp.namespace }}
spec:
  project: {{ .Values.argocdApp.project }}
  source:
    repoURL: {{ .Values.argocdApp.source.repoURL }}
    targetRevision: {{ .Values.argocdApp.source.targetRevision }}
    path: {{ .Values.argocdApp.source.path }}
    helm:
      valuesObject:
        name: {{ .Values.name }}
        namespace: {{ .Values.namespace }}
        networkPeer: {{ .Values.networkPeer }}
        owner:
          user: {{ .Values.owner.user }}
        helmRelease:
          chart:
            version: {{ .Values.helmRelease.chart.version | quote }}
          values: {{ .Values.helmRelease.values | toYaml | nindent 12 }}
  destination:
    # server: {{ .Values.argocdApp.destination.server }}
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
