apiVersion: management.loft.sh/v1
kind: VirtualClusterInstance
metadata:
  name: {{ .Values.name }}-simple
  namespace: {{ .Values.namespace }}
spec:
  networkPeer: {{ .Values.networkPeer }}
  owner:
    user: {{ .Values.owner.user }}
  template:
    accessPoint:
      ingress: {}
    helmRelease:
      chart:
        version: {{ .Values.helmRelease.chart.version | quote }}
      values: |
        {{ .Values.helmRelease.values | toYaml | nindent 8 | trim }}
    instanceTemplate:
      metadata: {}
    metadata: {}
    pro: {}
    spaceTemplate:
      metadata: {}
